# The data of a player: with storage x,y,z,world and lvl and Cycle data




# crates-num:
#   x: int
#   y: int
#   z: int
#   world: str
#   type: str

cycle:
  hasStarted: false
  crates:

# name:
  # storageX: double
  # storageY: double
  # storageZ: double
  # storageWorld: str
  # lvl: float

players:
